### ISSUE TITLE
on linux, unicode parameters cannot be longer than 128

### ISSUE THREAD

**Issue by kaiaeberli** [jiangwen365/pypyodbc#27]
I noticed the following when posting a query from linux using parameters:

If the parameter string is longer than 127 characters, pypyodbc will throw an error on row 1572 when trying this:

`param_buffer.value = c_char_buf`

It complains that c_char_buf is too large.

I checked: c_char_buf is created by UCS_buf() if parameter type is 'u' (unicode less than 255 characters):

```
c_char_buf = UCS_buf(param_val)
c_buf_len = len(c_char_buf)
```

UCS_buf(string) is defined to return encoding(utf-16-le) for linux, and return its argument for windows.

Thus on linux, due to 2 byte minimum char width for utf-16, the length of the byte array will be double the length of the underlying string.

As param_buffer.value size is defined as 255 no matter what platform, this leads to above error.

My fix was to double the buffer size for linux:

```
 if param_types[col_num][0] == 'u':
                sql_c_type = SQL_C_WCHAR
                sql_type = SQL_WVARCHAR 
                if sys.platform not in ('win32','cli'):
                          buf_size = 255 * 2 # double buffer size for linux                 
                else:
                         buf_size = 255
                ParameterBuffer = create_buffer_u(buf_size)   
```

Hope this helps someone.

**Comment by dmfreemon** [comment]
Related, see PR:
https://github.com/jiangwen365/pypyodbc/pull/73/files

**Comment by emohnish** [comment]
Hi 

I am also getting this error while saving more that 127 characters in Unix environment. I have applied above fix but still issue persists. Please let me know how to proceed.

Its has been above 2 months we are finding the solution of this issue. FYI... using pypyodbc 1.3.4 version.

Thanks

**Comment by AlexGriffiths** [comment]
Thank you so much for this. I was desperately trying to figure out why some text could not be inserted into a table where the columns where clearly large enough to support it. 

It's such a relief to have this sorted!

**Comment by timjen3** [comment]
An alternative that works for me is to pass encoded bytes as parameters. I'm working with SQL Server and pypyodbc 1.3.4.3

For example:
`
cursor = pypyodbc.connect(connection_string).cursor()
city= "Louisville".encode("utf-8", "ignore")[:32]
state = "KY".encode("utf-8", "ignore")[:2]
uid = "UID123".encode("utf-8", "ignore")[:16]
cursor.execute("UPDATE MyTable SET City=?, State=? WHERE Id=?", (city, state, uid))
`

I purposefully left the byte-trunacting in (ie: [:32]) because that works properly.

**Comment by braian87b** [comment]
handled fix https://github.com/jiangwen365/pypyodbc/pull/73#issuecomment-401458300
