### ISSUE TITLE
Version 1.3.3 removed from pypi

### ISSUE THREAD

**Issue by Smirl** [jiangwen365/pypyodbc#45]
With the recent release of 1.3.4 and 1.3.5 it looks like the 1.3.3 package has been removed from pypi.
Upgrading to the latest version isn't trivial as 1.3.4+ includes breaking changes (despite only being a minor version bump) .
We have worked around this problem by keeping a local mirror of it, but others might see issues such as production servers not provisioning, builds failing, or local dev workflow interupted.

Could this package be added to pypi again?

URL:
https://pypi.python.org/simple/pypyodbc/

OUTPUT:
```
Links for pypyodbc

pypyodbc-1.3.4.1.zip
pypyodbc-1.2.1.zip
pypyodbc-1.3.4.3.zip
pypyodbc-1.3.1.zip
pypyodbc-1.3.0.zip
pypyodbc-1.3.2.zip
pypyodbc-1.3.5.2.zip
```

**Comment by jiangwen365** [comment]
Hi, I reuploaded pypyodbc-1.3.3.1.zip - the previous file was deleted by mistake, and the PyPI system only allows me to use a different name, that's why there's an extra .1 in the file name.

**Comment by Smirl** [comment]
Thanks for fixing it so fast. Shame it couldn't keep the same name. For others which might have the same issue, they are the same version.
```
MD5 (pypyodbc-1.3.3.1.zip) = 4752bfb7d3574d99b13b6836f755f346
MD5 (pypyodbc-1.3.3.zip) = 4752bfb7d3574d99b13b6836f755f346
```
