### ISSUE TITLE
Sequentially inserting multiple rows in accessdb

### ISSUE THREAD

**Issue by dhanababum** [jiangwen365/pypyodbc#49]
Hi, I'm using pyodbc to insert multiple rows with sequential order, But pyodbc inserting rows in random order. Is this normal ?

For understanding I'm giving example,

params = [ ('A', 1), ('B', 2), ('C', 3), ('D', 4) ]
executemany("insert into t(name, id) values (?, ?)", params)

But in table, I can see order like this,

![image](https://cloud.githubusercontent.com/assets/5729855/24096791/19b8cc64-0d89-11e7-81f1-b68737befa39.png)

**Comment by jiangwen365** [comment]
hi, database do not care about orders itself, so it is quite normal you see it is randomly showed. it shows you in order only when you say how to order in an query.
