### ISSUE TITLE
ValueError for microseconds when using TDS >7.3

### ISSUE THREAD

**Issue by tappoz** [jiangwen365/pypyodbc#53]
I am currently using an Azure SQL Server database and found out that I had to modify the way `pypyodbc` is handling microseconds in `dttm_cvt(x)` at line 592 from `x[20:].ljust(6,'0')` to `x[20:26].ljust(6,'0')`. Otherwise I get: `ValueError: microsecond must be in 0..999999`.

This may be related to https://github.com/jiangwen365/pypyodbc/issues/26

Information about my setup:

- `SELECT @@VERSION;` gives `Microsoft SQL Azure (RTM) - 12.0.2000.8   Feb  8 2017 04:15:27   Copyright (C) 2016 Microsoft Corporation. All rights reserved.`
- `SELECT CONVERT(BINARY(4), (SELECT TOP 1 protocol_version from sys.dm_exec_connections)) AS TDS_VERSION;` gives `0x74000004` which afaik should be TDS version 7.4
- my ODBC connection string starts with: `DRIVER={SQL Server Native Client 11.0};`

Cf. also these variable length data types: https://msdn.microsoft.com/en-us/library/dd358341.aspx 
where they say:
```
 DATETIMNTYPE        =   %x6F  ; (see below)
 DATENTYPE           =   %x28  ; (introduced in TDS 7.3)
 TIMENTYPE           =   %x29  ; (introduced in TDS 7.3)
 DATETIME2NTYPE      =   %x2A  ; (introduced in TDS 7.3)
 DATETIMEOFFSETNTYPE =   %x2B  ; (introduced in TDS 7.3)
```

**Comment by jiangwen365** [comment]
Thanks, changed the code accordingly.

**Comment by tappoz** [comment]
Thank you :) Is there any news on when this could be included in a future release?
