### ISSUE TITLE
Missing License file / License is unclear

### ISSUE THREAD

**Issue by jacobsantos** [jiangwen365/pypyodbc#58]
Doing some research, it appears the license is MIT, but it is also unclear who holds the copyright.

I haven't looked too deeply into RealPyODBC, so I am not sure if the copyright info is there. The only thing I found was confirmation that at some point MIT license was applied.

If you could add license and copyright infomation, that would be great. I would not consider Pypi repository definitive for license info as it could be mistaken. Would rather that be available with the source.

**Comment by gordthompson** [comment]
I seem to have found the ["original"](http://web.archive.org/web/20051223214226/http://unipex.it:80/vario/RealPyOdbc.py) via archive.org. I spot-checked a few of the more recent captures (up to 2013) and found no evidence that Michele ever asserted Copyright, although it is my understanding that in some jurisdictions Copyright automatically attaches to the creator even if they do not explicitly claim it. Still, the current pypyodbc.py says

> \# Copyright (c) 2017 Henry Zhou <jiangwen365@gmail.com> and PyPyODBC contributors
> \# Copyright (c) 2004 Michele Petrazzo

As for license, the RealPyOdbc.py code has always stated

> \# This software if released with MIT Licence

so if we assume (in good faith) that "if" -> "is" then the conclusion would be that the MIT license has applied all along.

**Comment by braian87b** [comment]
https://github.com/jiangwen365/pypyodbc/blob/master/LICENSE
