### ISSUE TITLE
autocommit does not work like pyodbc

### ISSUE THREAD

**Issue by AlainBouchard** [jiangwen365/pypyodbc#64]
I am trying to move away from pyodbc and I switched to pypyodbc.  The autocommit=True, either on the .connect() or conn.autocommit=True, does not work like pyodbc.   I get the following message:

pypyodbc.ProgrammingError: ('42000', '[42000] [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]CREATE DATABASE statement not allowed within multi-statement transaction.')

...When creating a snapshot (so a database):
            my_cursor.execute("IF EXISTS (SELECT database_id FROM sys.databases WHERE NAME='{0}') DROP DATABASE {0}".format(my_snapshot))
            my_cursor.execute("CREATE DATABASE {0} ON ( NAME = {1}, FILENAME = N'{2}') AS SNAPSHOT OF {1}".format(my_snapshot, database, my_snapshot_file))

Note:  It works just fine with pyodbc

Thanks

**Comment by plannigan** [comment]
Looking at the implementation quickly, it looks like the autocommit mode is only set when the connection is made. Setting the `autocommit` variable on the connection does not effect the underlying ODBC connection. Where as `pyodbc` does [change the underlying connection attributes ](https://github.com/mkleehammer/pyodbc/blob/a3693bf175a32e6c3cea9c5c3be65acdae5467f2/src/connection.cpp#L940)when the property is assigned to.
