### ISSUE TITLE
Selecting a uniqueidentifier field returns a string that looks like bytes

### ISSUE THREAD

**Issue by junctionapps** [jiangwen365/pypyodbc#78]
I'm not sure if I'm doing something wrong, however, if I select a uuid field from ms sql the console appears to display it as a bytes object by prefixing with b, however, it is actually a str quoted with b''. To get the uuid you need to slice with row['itemid'][2:-1]

Is that the desired behaviour? Caused some grief when trying to insert the value into another table.

```
    cursor.execute("select voucher_draft.ItemID, voucher_draft.comments "
                   "from voucher_draft "
                   "where voucher_draft.ExpenseRef = ?", ('1234123412345', ))
    row = cursor.fetchone()
    print(row['itemid'])
    # yields: b'B335FDAD-DE0B-41DA-BB07-0DA10C04D59A'
    print(type(row['itemid']))
    # yields: <class 'str'>
    print(row['itemid'].upper())
    # yields: B'B335FDAD-DE0B-41DA-BB07-0DA10C04D59A'
    # note the uppercase B 
```

**Comment by braian87b** [comment]
First do a `pypyodbc.__file__` to see your pypyodbc library location

```
import pypyodbc; pypyodbc.__file__
'/usr/local/lib/python2.7/site-packages/pypyodbc.pyc'
```

Search for this block of code on your pypyodbc.py:

                elif param_types[col_num][0] in ('i','l','f'):
                    if py_v3:
                        c_char_buf = bytes(str(param_val),'ascii')
                    else:
                        c_char_buf = str(param_val)
                    c_buf_len = len(c_char_buf)

And try removing the `str()` functions one at a time for each one of those lines, I am sure that is probably the fault of some of those, I am not very familiar with Python3, but it is maybe the bytes function too, since the b at the beggining it means that is a bytestring python3 type instead of a normal string that is unicode.

Mh, Now Im thinking, no, probably is not that, probably is this line...

    SQL_GUID            : (str,                 str,                        SQL_C_CHAR,         create_buffer,      2048  ,         False         ),

change it by:


    SQL_GUID            : (str,                 lambda x: x,                SQL_C_CHAR,         create_buffer,      2048  ,         False         ),

Like on the `SQL_VARCHAR` line.

Let me know your findings please.

**Comment by junctionapps** [comment]
Okay, with the following where itemid is a ms sql uniqueidentifier
SQL version from select @@VERSION;

> (Microsoft SQL Server 2008 R2 (RTM) - 10.50.1600.1 (X64)   Apr  2 2010 15:48:46   Copyright (c) Microsoft Corporation  Enterprise Edition (64-bit) on Windows NT 6.1 <X64> (Build 7601: Service Pack 1) (Hypervisor) ) 

```
    print(row)
    print(row['itemid'])
    print(type(row['itemid']))
```
Baseline testing prior to changes result:

> ("b'5000EB67-5E5E-4828-8D2E-50DD2CDAD800'", 'Test of Python Voucher Import')
> b'5000EB67-5E5E-4828-8D2E-50DD2CDAD800'
> <class 'str'>

After change to 
`SQL_GUID            : (str,                 lambda x: x,                SQL_C_CHAR,         create_buffer,      2048  ,         False         ),`

> (b'5000EB67-5E5E-4828-8D2E-50DD2CDAD800', 'Test of Python Voucher Import')
> b'5000EB67-5E5E-4828-8D2E-50DD2CDAD800'
> <class 'bytes'>

To me that seems to solve my issue. Thank you for the help! I suspect you will manage a pull request, however, I can if needed.

**Comment by braian87b** [comment]
@junctionapps  Thanks for write down here your findings, yes, please if you can post a pull request.
